### ISSUE TITLE
TT version garrison script error

### ISSUE THREAD

**Issue by Xeno69** [Xeno69/Domination#292]
![20210616214325_1-1.jpg](https://user-images.githubusercontent.com/3141271/122281492-9c025600-ceea-11eb-95c8-e63cf85b5e47.jpg)

**Comment by longtimegamer** [comment]
I assume this is related to https://github.com/Xeno69/Domination/pull/291

Can we revert that pull request?

**Comment by Xeno69** [comment]
I didn't get that error, it seems TT related only. Have to look at it tomorrow

**Comment by Xeno69** [comment]
Should be fixed in 4.55

**Comment by longtimegamer** [comment]
Uh oh, issue still occurs.  I guess it wasn't related to #291 ...

18:56:17 "Internal D Version: 4.55"
18:56:17 "DOM initializing revive"
18:56:17 [21566,91.47,15.156,"Dom x_setupplayer.sqf processed"]
18:56:17 [21567,91.509,15.256,"Dom intro started"]
18:56:23 Loading movesType CfgMovesSnakes_F
18:56:23 Reading cached action map data
18:56:25 Loading movesType CfgMovesButterfly
18:56:25 Reading cached action map data
18:56:30 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
18:56:30 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[3687.78,13776.1,0],"_grp",R Alpha 1-1]
18:56:30 "Zen_Occupy House Error : No units given."
18:56:30 Error in expression < d_fnc_garrisonUnits;
d_delinfsm append _unitstog;

sleep 0.1;






private _wp>
18:56:30   Error position: <_unitstog;

sleep 0.1;






private _wp>
18:56:30   Error Undefined variable in expression: _unitstog
18:56:30 File C:\Users\neily_yblyyb7\Documents\Arma 3 - Other Profiles\Longtime\mpmissions\longtimegamer\Domination\co30_Domination.Altis\server\fn_createmaintarget.sqf..., line 269
18:56:31 I_APC_Wheeled_03_cannon_F: indicator_com_smoke_1 - unknown animation source smoke_source
18:56:31 I_APC_Wheeled_03_cannon_F: indicator_com_smoke_2 - unknown animation source smoke_source
18:56:31 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:",GUER]
18:56:31 Duplicate HitPoint name 'HitTurret' in 'I_MRAP_03_gmg_F'
18:56:31 Duplicate HitPoint name 'HitGun' in 'I_MRAP_03_gmg_F'
18:56:32 I_Truck_02_transport_F: door_lf - unknown animation source door (defined in AnimationSources::Door_LF)
18:56:32 I_Truck_02_transport_F: door_rf - unknown animation source door (defined in AnimationSources::Door_RF)
18:56:32 Duplicate HitPoint name 'HitGun' in 'I_HMG_01_high_F'
18:56:32 Duplicate HitPoint name 'HitTurret' in 'I_HMG_01_high_F'
18:56:32 Dimensions in class I_HMG_01_high_F should be an array of size 2.
18:56:32 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
18:56:32 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[4102.91,13750.8],"_grp",R Alpha 1-5]
18:56:32 I_Truck_02_transport_F: door_lf - unknown animation source door (defined in AnimationSources::Door_LF)
18:56:32 I_Truck_02_transport_F: door_rf - unknown animation source door (defined in AnimationSources::Door_RF)
18:56:33 I_APC_tracked_03_cannon_F: cannon_ready_light - unknown animation source muzzle_hide_cannon
18:56:33 Duplicate HitPoint name 'HitGun' in 'I_HMG_02_F'
18:56:33 Duplicate HitPoint name 'HitTurret' in 'I_HMG_02_F'
18:56:33 Dimensions in class I_HMG_02_F should be an array of size 2.
18:56:34 Duplicate HitPoint name 'HitGun' in 'I_HMG_01_F'
18:56:34 Duplicate HitPoint name 'HitTurret' in 'I_HMG_01_F'
18:56:34 Dimensions in class I_HMG_01_F should be an array of size 2.
18:56:34 Duplicate HitPoint name 'HitGun' in 'I_GMG_01_A_F'
18:56:34 Duplicate HitPoint name 'HitTurret' in 'I_GMG_01_A_F'
18:56:34 Dimensions in class I_GMG_01_A_F should be an array of size 2.
18:56:35 Warning: Convex component representing Track_L not found
18:56:35 Warning: Convex component representing Track_R not found
18:56:35 Warning: Convex component representing Slide not found
18:56:35 I_LT_01_AT_F: cannon_ready_light - unknown animation source muzzle_hide_cannon
18:56:35 I_LT_01_AT_F: indicator_com_turret_mfd_driver - unknown animation source obsturret
18:56:35 I_LT_01_AT_F: indicator_com_turret_mfd_gunner - unknown animation source obsturret
18:56:35 unable to connect anim. source "Hit" to hitpoint "HitComTurret" in I_LT_01_AT_F
18:56:35 Loading movesType CfgMovesRabbit_F
18:56:35 Reading cached action map data
18:56:39 [22706,112.754,36.635,"Dom intro ended"]
18:56:39 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
18:56:39 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[3687.78,13776.1,0],"_grp",R Alpha 4-4]
18:56:39 "Zen_Occupy House Error : No units given."
18:56:39 Error in expression < d_fnc_garrisonUnits;
d_delinfsm append _unitstog;
};
};


if (d_ovrw_cnt > 0) t>
18:56:39   Error position: <_unitstog;
};
};


if (d_ovrw_cnt > 0) t>
18:56:39   Error Undefined variable in expression: _unitstog
18:56:39 File C:\Users\neily_yblyyb7\Documents\Arma 3 - Other Profiles\Longtime\mpmissions\longtimegamer\Domination\co30_Domination.Altis\server\fn_createmaintarget.sqf..., line 446
18:56:39 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
18:56:39 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[3687.78,13776.1,0],"_grp",R Alpha 4-4]
18:56:39 "Zen_Occupy House Error : No units given."
18:56:39 Error in expression < d_fnc_garrisonUnits;
d_delinfsm append _unitstog;
};
};


if (d_ovrw_cnt > 0) t>
18:56:39   Error position: <_unitstog;
};
};


if (d_ovrw_cnt > 0) t>
18:56:39   Error Undefined variable in expression: _unitstog
18:56:39 File C:\Users\neily_yblyyb7\Documents\Arma 3 - Other Profiles\Longtime\mpmissions\longtimegamer\Domination\co30_Domination.Altis\server\fn_createmaintarget.sqf..., line 446
18:56:39 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
18:56:39 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[3687.78,13776.1,0],"_grp",R Alpha 4-4]
18:56:39 "Zen_Occupy House Error : No units given."
18:56:40 Error in expression < d_fnc_garrisonUnits;
d_delinfsm append _unitstog;
};
};


if (d_ovrw_cnt > 0) t>
18:56:40   Error position: <_unitstog;
};
};


if (d_ovrw_cnt > 0) t>
18:56:40   Error Undefined variable in expression: _unitstog
18:56:40 File C:\Users\neily_yblyyb7\Documents\Arma 3 - Other Profiles\Longtime\mpmissions\longtimegamer\Domination\co30_Domination.Altis\server\fn_createmaintarget.sqf..., line 446
18:56:40 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
18:56:40 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[3687.78,13776.1,0],"_grp",R Alpha 4-4]
18:56:40 "Zen_Occupy House Error : No units given."
18:56:40 Error in expression < d_fnc_garrisonUnits;
d_delinfsm append _unitstog;
};
};


if (d_ovrw_cnt > 0) t>
18:56:40   Error position: <_unitstog;
};
};


if (d_ovrw_cnt > 0) t>
18:56:40   Error Undefined variable in expression: _unitstog
18:56:40 File C:\Users\neily_yblyyb7\Documents\Arma 3 - Other Profiles\Longtime\mpmissions\longtimegamer\Domination\co30_Domination.Altis\server\fn_createmaintarget.sqf..., line 446
18:56:40 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
18:56:40 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[3687.78,13776.1,0],"_grp",R Alpha 4-4]
18:56:40 "Zen_Occupy House Error : No units given."
18:56:40 Error in expression < d_fnc_garrisonUnits;
d_delinfsm append _unitstog;
};
};


if (d_amb_cnt > 0) th>
18:56:40   Error position: <_unitstog;
};
};


if (d_amb_cnt > 0) th>
18:56:40   Error Undefined variable in expression: _unitstog
18:56:40 File C:\Users\neily_yblyyb7\Documents\Arma 3 - Other Profiles\Longtime\mpmissions\longtimegamer\Domination\co30_Domination.Altis\server\fn_createmaintarget.sqf..., line 463
18:56:40 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
18:56:40 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[3687.78,13776.1,0],"_grp",R Alpha 4-4]
18:56:40 "Zen_Occupy House Error : No units given."
18:56:40 Error in expression < d_fnc_garrisonUnits;
d_delinfsm append _unitstog;
};
};


if (d_amb_cnt > 0) th>
18:56:40   Error position: <_unitstog;
};
};


if (d_amb_cnt > 0) th>
18:56:40   Error Undefined variable in expression: _unitstog
18:56:40 File C:\Users\neily_yblyyb7\Documents\Arma 3 - Other Profiles\Longtime\mpmissions\longtimegamer\Domination\co30_Domination.Altis\server\fn_createmaintarget.sqf..., line 463
18:56:40 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
18:56:40 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[3687.78,13776.1,0],"_grp",R Alpha 4-4]
18:56:40 "Zen_Occupy House Error : No units given."
18:56:40 Error in expression < d_fnc_garrisonUnits;
d_delinfsm append _unitstog;
};
};

if (d_snp_cnt == 0) ex>
18:56:40   Error position: <_unitstog;
};
};

if (d_snp_cnt == 0) ex>
18:56:40   Error Undefined variable in expression: _unitstog
18:56:40 File C:\Users\neily_yblyyb7\Documents\Arma 3 - Other Profiles\Longtime\mpmissions\longtimegamer\Domination\co30_Domination.Altis\server\fn_createmaintarget.sqf..., line 480
18:56:40 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
18:56:40 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[3687.78,13776.1,0],"_grp",R Alpha 4-4]
18:56:41 "Zen_Occupy House Error : No units given."
18:56:41 Error in expression < d_fnc_garrisonUnits;
d_delinfsm append _unitstog;
};
};

if (d_snp_cnt == 0) ex>
18:56:41   Error position: <_unitstog;
};
};

if (d_snp_cnt == 0) ex>
18:56:41   Error Undefined variable in expression: _unitstog
18:56:41 File C:\Users\neily_yblyyb7\Documents\Arma 3 - Other Profiles\Longtime\mpmissions\longtimegamer\Domination\co30_Domination.Altis\server\fn_createmaintarget.sqf..., line 480
18:57:43 Duplicate HitPoint name 'HitTurret' in 'I_MRAP_03_hmg_F'
18:57:43 Duplicate HitPoint name 'HitGun' in 'I_MRAP_03_hmg_F'
19:01:31 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
19:01:31 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[7849.68,18010.3,0],"_grp",R Alpha 1-4]
19:01:31 ["Attention in getunitlistm!!! Current _grptype returns nil, _grptype:","allmen",", _side:","G"]
19:01:31 ["Attention, _unitlist (param 2) is empty, returning []","_pos",[7849.68,18010.3,0],"_grp",R Alpha 3-2]
19:01:33 Warning: Convex component representing Track_L not found
19:01:33 Warning: Convex component representing Track_R not found
19:01:33 Warning: Convex component representing Slide not found
19:01:33 I_LT_01_AA_F: cannon_ready_light - unknown animation source muzzle_hide_cannon
19:01:33 I_LT_01_AA_F: indicator_com_turret_mfd_driver - unknown animation source obsturret

**Comment by Xeno69** [comment]
Vanilla?

**Comment by longtimegamer** [comment]
My favorite flavor.

I'm just copying the mission.sqm and x_setup.sqf and then running from the editor -> Run As Multiplayer.  The error immediately occurs.

**Comment by Xeno69** [comment]
No error here when I execute "Run As Multiplayer"

Somewhere on your side d_allmen_g is missing. In the CLSA version they are missing.

**Comment by longtimegamer** [comment]
This was for Altis.  I noticed no __TTALTIS__ was defined.  I think #294 will fix this.

**Comment by Xeno69** [comment]
Closing this now as I was never able to reproduce it.
